In [54]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

In [3]:
data=pd.read_csv('data/output_updated.csv')
data.shape

(301768, 27)

In [4]:
data.columns

Index(['Banner', 'id', 'UPC', 'StoreID', 'Date', 'RegPrice', 'AKHIFlag',
       'PromoPrice', 'UPCBANPriceMean', 'UPCBANPriceStDev', 'UPCNATPriceMean',
       'UPCNATPriceStDev', 'UPCBANTotalPrevalence', 'UPCBANWeeksAtPrice',
       'Banner_Volatility_Metric', 'National_Volatility_Metric',
       'Banner Acceptable Variance', 'Banner Control Limits',
       'National Control Limits', 'decision1', 'decision2', 'decision3',
       'decision4', 'decision5', 'decision6', 'Result_code_number',
       'Result_code'],
      dtype='object')

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301768 entries, 0 to 301767
Data columns (total 27 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Banner                      301768 non-null  object
 1   id                          301768 non-null  int64
 2   UPC                         301767 non-null  float64
 3   StoreID                     301768 non-null  int64
 4   Date                        301768 non-null  object
 5   RegPrice                    301768 non-null  float64
 6   AKHIFlag                    301768 non-null  int64
 7   PromoPrice                  18994 non-null   float64
 8   UPCBANPriceMean             279536 non-null  float64
 9   UPCBANPriceStDev            279012 non-null  float64
 10  UPCNATPriceMean             284244 non-null  float64
 11  UPCNATPriceStDev            283872 non-null  float64
 12  UPCBANTotalPrevalence       276663 non-null  float64
 13  UPCBANWeeksAtPrice          276663 non-null  float64
 14  Banner_Volatility_Metric    279012 non-null  float64
 15  National_Volatility_Metric  283872 non-null  float64
 16  Banner Acceptable Variance  278841 non-null  float64
 17  Banner Control Limits       278841 non-null  float64
 18  National Control Limits     283375 non-null  float64
 19  decision1                   301768 non-null  object
 20  decision2                   265559 non-null  object
 21  decision3                   22484 non-null   object
 22  decision4                   22588 non-null   object
 23  decision5                   36859 non-null   object
 24  decision6                   36208 non-null   object
 25  Result_code_number          301768 non-null  int64
 26  Result_code                 301768 non-null  object
dtypes: float64(14), int64(4), object(9)
memory usage: 62.2+ MB

In [55]:
data.head(2)

,Banner,id,UPC,StoreID,Date,RegPrice,AKHIFlag,PromoPrice,UPCBANPriceMean,UPCBANPriceStDev,UPCNATPriceMean,UPCNATPriceStDev,UPCBANTotalPrevalence,UPCBANWeeksAtPrice,Banner_Volatility_Metric,National_Volatility_Metric,Banner Acceptable Variance,Banner Control Limits,National Control Limits,decision1,decision2,decision3,decision4,decision5,decision6,Result_code_number,Result_code
0,Walmart Inc,43532739003,0.0,1000507,2023-07-03,9.98,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fail,NaN,NaN,NaN,Fail,NaN,7,Accept
1,Walmart Inc,43532739499,0.0,1000507,2023-07-03,9.98,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fail,NaN,NaN,NaN,Fail,NaN,7,Accept

In [18]:
data.isnull().sum()

Banner                             0
id                                 0
UPC                                1
StoreID                            0
Date                               0
RegPrice                           0
AKHIFlag                           0
PromoPrice                    282774
UPCBANPriceMean                22232
UPCBANPriceStDev               22756
UPCNATPriceMean                17524
UPCNATPriceStDev               17896
UPCBANTotalPrevalence          25105
UPCBANWeeksAtPrice             25105
Banner_Volatility_Metric       22756
National_Volatility_Metric     17896
Banner Acceptable Variance     22927
Banner Control Limits          22927
National Control Limits        18393
decision1                          0
decision2                      36209
decision3                     279284
decision4                     279180
decision5                     264909
decision6                     265560
Result_code_number                 0
Result_code                        0
dtype: int64

In [17]:
#data type conversion
data["Date"]=pd.to_datetime(data['Date'])

# Convert 'DateColumn' to the desired date format ('yyyy-mm-dd')
data["Date"]=data["Date"].dt.strftime('%Y-%m-%d')

In [28]:
# data.loc[data["Date"]>="2023-07-05"]

,Banner,id,UPC,StoreID,Date,RegPrice,AKHIFlag,PromoPrice,UPCBANPriceMean,UPCBANPriceStDev,...,Banner Control Limits,National Control Limits,decision1,decision2,decision3,decision4,decision5,decision6,Result_code_number,Result_code
642,H E Butt Grocery Co/HQ,43592118452,6.132400e+04,106180,2023-07-05,9.98,0,NaN,10.236910,0.910014,...,0.35,0.3,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
643,H E Butt Grocery Co/HQ,43592174181,1.066808e+09,106180,2023-07-05,7.88,0,NaN,7.932598,0.086940,...,0.25,0.2,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
644,H E Butt Grocery Co/HQ,43592415380,1.115217e+09,106180,2023-07-05,2.18,0,NaN,2.091037,0.364982,...,0.45,0.5,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
645,H E Butt Grocery Co/HQ,43591977071,1.121001e+09,106180,2023-07-05,1.90,0,NaN,1.694444,0.036838,...,0.25,0.3,Fail,NaN,NaN,NaN,Pass,Pass,6,Accept
646,H E Butt Grocery Co/HQ,43592189211,1.410007e+09,106180,2023-07-05,3.34,0,NaN,3.347761,0.032888,...,0.25,0.3,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298518,Walmart Inc,43598838361,8.561660e+10,992396,2023-07-05,13.97,0,NaN,13.972256,0.082496,...,0.25,0.2,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
298519,Walmart Inc,43598836989,8.600089e+10,992396,2023-07-05,2.98,0,NaN,2.993729,0.043467,...,0.25,0.2,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
298520,Walmart Inc,43598831608,8.813340e+10,992396,2023-07-05,13.99,0,NaN,12.975077,0.125484,...,0.25,0.3,Fail,rPass,NaN,rPass,Pass,Pass,6,Accept
298521,Walmart Inc,43598846113,8.879617e+10,992396,2023-07-05,3.72,0,NaN,3.720000,0.000000,...,0.25,0.2,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept
298522,Walmart Inc,43598846071,8.879617e+10,992396,2023-07-05,1.27,0,NaN,1.273828,0.080618,...,0.35,0.3,Pass,Pass,NaN,NaN,NaN,NaN,1,Accept

In [13]:
#Accept Rate   (Volume)

data_accept_rate=data['Result_code'].value_counts()
round(data_accept_rate["Accept"]/(data_accept_rate["Accept"]+data_accept_rate["Reject"])*100,2)

98.84

In [26]:
# Date Values 

date_min_value=data["Date"].min()
date_max_value=data["Date"].max()
date_min_value,date_max_value

('2023-06-30', '2023-07-05')

In [29]:
data.columns

Index(['Banner', 'id', 'UPC', 'StoreID', 'Date', 'RegPrice', 'AKHIFlag',
       'PromoPrice', 'UPCBANPriceMean', 'UPCBANPriceStDev', 'UPCNATPriceMean',
       'UPCNATPriceStDev', 'UPCBANTotalPrevalence', 'UPCBANWeeksAtPrice',
       'Banner_Volatility_Metric', 'National_Volatility_Metric',
       'Banner Acceptable Variance', 'Banner Control Limits',
       'National Control Limits', 'decision1', 'decision2', 'decision3',
       'decision4', 'decision5', 'decision6', 'Result_code_number',
       'Result_code'],
      dtype='object')

In [30]:
data.columns

Index(['Banner', 'id', 'UPC', 'StoreID', 'Date', 'RegPrice', 'AKHIFlag',
       'PromoPrice', 'UPCBANPriceMean', 'UPCBANPriceStDev', 'UPCNATPriceMean',
       'UPCNATPriceStDev', 'UPCBANTotalPrevalence', 'UPCBANWeeksAtPrice',
       'Banner_Volatility_Metric', 'National_Volatility_Metric',
       'Banner Acceptable Variance', 'Banner Control Limits',
       'National Control Limits', 'decision1', 'decision2', 'decision3',
       'decision4', 'decision5', 'decision6', 'Result_code_number',
       'Result_code'],
      dtype='object')

In [31]:
data.head(2)

,Banner,id,UPC,StoreID,Date,RegPrice,AKHIFlag,PromoPrice,UPCBANPriceMean,UPCBANPriceStDev,...,Banner Control Limits,National Control Limits,decision1,decision2,decision3,decision4,decision5,decision6,Result_code_number,Result_code
0,Walmart Inc,43532739003,0.0,1000507,2023-07-03,9.98,0,NaN,NaN,NaN,...,NaN,NaN,Fail,NaN,NaN,NaN,Fail,NaN,7,Accept
1,Walmart Inc,43532739499,0.0,1000507,2023-07-03,9.98,0,NaN,NaN,NaN,...,NaN,NaN,Fail,NaN,NaN,NaN,Fail,NaN,7,Accept

In [32]:
data.groupby('Banner')['Result_code'].value_counts()

Banner                     Result_code
Academy Sports & Outdoors  Accept           1279
                           Reject             15
Ahold Delhaize USA         Accept           3459
                           Reject             41
Albertsons Companies Inc   Accept           4421
                                           ...
Walmart Inc                Accept         212741
                           Reject           2661
Wegmans Food Markets Inc   Accept           1991
                           Reject             13
Weis Markets Inc HQ        Accept            309
Name: count, Length: 135, dtype: int64

In [38]:
banner_scores = data[data['Result_code'] == 'Accept'].groupby('Banner').size() / data.groupby('Banner').size()
banner_scores *= 100
banner_scores.name = 'Score'

In [45]:
banner_accept_count = data[data['Result_code'] == 'Accept'].groupby('Banner').size()
banner_total_count = data.groupby('Banner').size()
banner_scores = (banner_accept_count / banner_total_count * 100).round(2)

# Create a DataFrame with 'Score' and 'Count' columns for each 'Banner'
banner_scores_df = pd.DataFrame({
    'Volume': banner_total_count,
    'Accept Rate': banner_scores
})

In [47]:
banner_scores_df.reset_index(inplace=True)

In [49]:
banner_scores_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Banner       87 non-null     object
 1   Volume       87 non-null     int64
 2   Accept Rate  87 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.2+ KB

In [50]:
#accepte rate week wise,

In [59]:
# data['week'] = data['Date'].dt.isocalendar().week

# Group the dataframe by week and get the count of 'Accept' and 'Reject' values
# weekly_result = data.groupby('week').agg(count=('Result_code', 'count'), accept_count=('Result_code', lambda x: x.eq('Accept').sum()))

# # Calculate the acceptance rate
# weekly_result['acceptance_rate'] = weekly_result['accept_count'] / weekly_result['count']

# # Create a new dataframe with the weekly results
# weekly_results_df = weekly_result.reset_index()

# # Print the weekly results dataframe
# print(weekly_results_df)

In [56]:
a=123456

In [ ]:
data["a,c"].groupby([""])